/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia5;

import guia5.Ventanasecundaria;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author VARGAS
 */
public class Frmguia2 extends javax.swing.JFrame {
    
    ArrayList<String> vector = new ArrayList<String>();
    int contador=0;
    String s="";
    int avance;
    private int progreso=10;
    
    /**
     * Creates new form Frmguia2
     */
    public Frmguia2() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOrdena = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAMostrar = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();
        btnGuardar = new javax.swing.JButton();
        txtDato = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guía 2");
        getContentPane().setLayout(null);

        btnOrdena.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnOrdena.setText("Ordenar datos");
        btnOrdena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenaActionPerformed(evt);
            }
        });
        getContentPane().add(btnOrdena);
        btnOrdena.setBounds(212, 125, 123, 25);

        btnMostrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMostrar.setText("Mostrar datos");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrar);
        btnMostrar.setBounds(212, 168, 123, 25);

        btnRegresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegresar.setText("Regresar ");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar);
        btnRegresar.setBounds(212, 338, 120, 25);

        txtAMostrar.setColumns(1);
        txtAMostrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAMostrar.setRows(10);
        jScrollPane1.setViewportView(txtAMostrar);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(68, 125, 94, 229);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setText("Introduzca 10 letras:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 40, 150, 19);
        getContentPane().add(ProgressBar);
        ProgressBar.setBounds(102, 86, 174, 21);

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        btnGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnGuardarKeyTyped(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(233, 45, 100, 23);

        txtDato.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatoActionPerformed(evt);
            }
        });
        txtDato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDatoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDatoKeyTyped(evt);
            }
        });
        getContentPane().add(txtDato);
        txtDato.setBounds(163, 38, 52, 30);

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(212, 295, 120, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Ventanasecundaria sec=new Ventanasecundaria();
        sec.setVisible(true);
        dispose();
 
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        avance=Math.round(100/10);
        
        if(contador<10 && !txtDato.getText().equals("")){
            ProgressBar.setValue(progreso);
            ProgressBar.setStringPainted(true);
            vector.add(txtDato.getText());
            contador++;
            txtDato.setText("");
            progreso=progreso+avance;
        }else if(contador>=10){
            JOptionPane.showMessageDialog(null, "Espacio lleno");
            txtDato.setText("");
        }
        txtDato.requestFocus();
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtDatoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatoKeyTyped
        
        char letra=evt.getKeyChar();
        String let=txtDato.getText();
        
        if(let.length()>0){
            evt.consume();
        }
        if(Character.isLetter(letra)){
        }else{
            evt.consume();
        }
    }//GEN-LAST:event_txtDatoKeyTyped

    private void btnOrdenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenaActionPerformed

        Collections.sort(vector);
         String salida="";
        for (int x=0;x<vector.size();x++){
         
         salida= salida+vector.get(x)+"\n";
        }
        
    }//GEN-LAST:event_btnOrdenaActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        s="";
        for (int x=0;x<vector.size();x++){
         
         s= s+vector.get(x)+"\n";
        }
        
        txtAMostrar.setText(s);
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtDato.setText("");
        txtAMostrar.setText("");
        vector.clear();
        contador=0;
        ProgressBar.setValue(0);
        progreso=10;
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnGuardarKeyTyped
        
    }//GEN-LAST:event_btnGuardarKeyTyped

    private void txtDatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatoActionPerformed

    private void txtDatoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            btnGuardarActionPerformed(null);
        }
    }//GEN-LAST:event_txtDatoKeyPressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frmguia2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frmguia2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frmguia2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frmguia2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frmguia2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnOrdena;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAMostrar;
    private javax.swing.JTextField txtDato;
    // End of variables declaration//GEN-END:variables
}
