/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia5;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author RICK LOPEZ
 */
public class Frmguia3y4 extends javax.swing.JFrame {

    /**
     * Creates new form Frmguia3y4
     */
    public Frmguia3y4() {
        initComponents();
        txtprincipal.setEnabled(false);
        setLocationRelativeTo(null);
        setTitle("App guia 3 y 4");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnucleos = new javax.swing.JTextField();
        txtpantalla = new javax.swing.JTextField();
        txtram = new javax.swing.JTextField();
        txtgarantia = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbmarca = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbxprincipal = new javax.swing.JCheckBox();
        cbxsecundaria = new javax.swing.JCheckBox();
        cbxflash = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        txtprincipal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtbateria = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txtsecundaria = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cpu numero de nucleos:");

        jLabel2.setText("Tamaño de pantalla:");

        jLabel3.setText("Cantidad de RAM:");

        jLabel4.setText("Tiempo de garantia:");

        jLabel5.setText("Precio:");

        txtnucleos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnucleosActionPerformed(evt);
            }
        });
        txtnucleos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnucleosKeyTyped(evt);
            }
        });

        txtpantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpantallaActionPerformed(evt);
            }
        });
        txtpantalla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpantallaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpantallaKeyTyped(evt);
            }
        });

        txtram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtramActionPerformed(evt);
            }
        });
        txtram.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtramKeyTyped(evt);
            }
        });

        txtgarantia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgarantiaActionPerformed(evt);
            }
        });
        txtgarantia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtgarantiaKeyTyped(evt);
            }
        });

        txtprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecioActionPerformed(evt);
            }
        });
        txtprecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprecioKeyTyped(evt);
            }
        });

        jLabel6.setText("PUNTAJE DE MOVILES");

        jLabel7.setText("Marca:");

        cmbmarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NEXUS", "GOOGLE", "LENOVO", "HUAWEI", "SONY", "APPLE", "SAMSUNG", "ALCATEL", "LG", "OTRA" }));

        jLabel8.setText("Camaras:");

        cbxprincipal.setText("Principal");
        cbxprincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxprincipalActionPerformed(evt);
            }
        });

        cbxsecundaria.setText("Secundaria");
        cbxsecundaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxsecundariaActionPerformed(evt);
            }
        });

        cbxflash.setText("Flash");
        cbxflash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxflashActionPerformed(evt);
            }
        });

        jButton1.setText("Ejecutar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtprincipal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprincipalKeyTyped(evt);
            }
        });

        jLabel9.setText("Bateria");

        txtbateria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbateriaKeyTyped(evt);
            }
        });

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtsecundaria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsecundariaKeyTyped(evt);
            }
        });

        texto.setColumns(20);
        texto.setRows(5);
        jScrollPane1.setViewportView(texto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtram, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtgarantia, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtnucleos, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(30, 30, 30)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cbxprincipal)
                                                .addComponent(txtprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtsecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cbxsecundaria))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtbateria)
                                    .addComponent(txtpantalla, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addComponent(cbxflash))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(42, 42, 42)
                                .addComponent(jButton2)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnucleos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtpantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtbateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtgarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbxsecundaria)
                    .addComponent(cbxprincipal)
                    .addComponent(cbxflash))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxprincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxprincipalActionPerformed
        // TODO add your handling code here:
        txtprincipal.setEnabled(true);
        txtprincipal.requestFocus();
    }//GEN-LAST:event_cbxprincipalActionPerformed

    private void txtpantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpantallaActionPerformed

    private void txtprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecioActionPerformed

    public double BateriaPantalla() {
        double puntajeBP = 0;
        double comp = Double.parseDouble(txtpantalla.getText());
        double ma = Double.parseDouble(txtbateria.getText());
        if (comp <= 4) {
            if (ma == 1200) {
                puntajeBP = 3;
            } else if (ma > 1200 && ma < 2400) {
                puntajeBP = 4;
            } else if (ma > 2400 && ma < 3100) {
                puntajeBP = 5;
            } else if (ma > 3100) {
                puntajeBP = 6;
            }
        } else if (comp == 5) {
            if (ma <= 1200) {
                puntajeBP = 1;
            } else if (ma > 1200 && ma < 2400) {
                puntajeBP = 2;
            } else if (ma > 2400 && ma < 3100) {
                puntajeBP = 3;
            } else if (ma > 3100) {
                puntajeBP = 4;
            }
        }
        return puntajeBP;
    }

    public int refDeMarca() {
        int ref = 0;
        if (cmbmarca.getSelectedItem() == "NEXUS" || cmbmarca.getSelectedItem() == "GOOGLE" || cmbmarca.getSelectedItem() == "LENOVO" || cmbmarca.getSelectedItem() == "HUAWEI" || cmbmarca.getSelectedItem() == "SONY" || cmbmarca.getSelectedItem() == "APPLE") {
            ref = 4;
        } else if (cmbmarca.getSelectedItem() == "SAMSUNG" || cmbmarca.getSelectedItem() == "ALCATEL" || cmbmarca.getSelectedItem() == "LG") {
            ref = 3;
        } else {
            ref = 2;
        }

        return ref;
    }

    public double rangoPrecio() {
        double rango = 0;
        double precio = Double.parseDouble(txtprecio.getText());
        if (precio < 100) {
            rango = 2;
        } else if (precio >= 100 && precio <= 350) {
            rango = 3;
        } else if (precio > 350) {
            rango = 4;
        }
        return rango;
    }

    public double pixelaje() {
        double pixel = 0;
        int camarap = Integer.parseInt(txtprincipal.getText());
        int camaras = Integer.parseInt(txtsecundaria.getText());
        if (camarap <= 5) {
            if (camaras <= 2) {
                pixel = 1;
            } else if (camaras > 2) {
                pixel = 2;
            }

        } else if (camarap > 5 && camarap <= 8) {
            if (camaras < 2) {
                pixel = 1;
            } else if (camaras >= 2 && camaras <= 3) {
                pixel = 2;
            } else if (camaras > 3) {
                pixel = 3;
            }
        } else if (camarap > 8) {
            if (camaras < 2) {
                pixel = 1;
            } else if (camaras >= 2 && camaras < 5) {
                pixel = 2;
            } else if (camaras > 5) {
                pixel = 3;
            }

        } else {
            pixel = pixel - 1;
        }

        return pixel;
    }

    public double garantia() {
        double garan = 0;
        int gara = Integer.parseInt(txtgarantia.getText());
        if (gara <= 3) {
            garan = 1;
        } else if (gara > 3 && gara < 6) {
            garan = 2;
        } else if (gara > 6) {
            garan = 4;
        }

        return garan;
    }

    public double CPU() {
        double cpu = 0;
        int valor = Integer.parseInt(txtnucleos.getText());
        if (valor == 2) {
            cpu = 0;
        } else if (valor == 4) {
            cpu = 1;
        } else if (valor == 6) {
            cpu = 2;
        } else if (valor == 8) {
            cpu = 3;
        }
        return cpu;
    }

    public double Ram() {
        double ram = 0.0;
        int Ram1 = Integer.parseInt(txtram.getText());
        if (Ram1 <= 1) {
            ram = 0;
        } else if (Ram1 > 1 && Ram1 < 2) {
            ram = 2;
        } else if (Ram1 > 2 && Ram1 < 4) {
            ram = 4;
        } else if (Ram1 > 4) {
            ram = 6;
        }
        return ram;
    }

    public void Impresion() {
        double impre = 0;
        impre = BateriaPantalla() + refDeMarca() + rangoPrecio() + pixelaje() + garantia() + CPU() + Ram();
        if (impre <= 7) {
            JOptionPane.showMessageDialog(this, "No es buena inversion");
        } else if (impre > 7 && impre <= 14) {
            JOptionPane.showMessageDialog(null, "Inversion de Riesgo");
        } else if (impre >= 15 && impre < 21) {
            JOptionPane.showMessageDialog(this, "Inversion viable");
        } else if (impre > 22) {
            JOptionPane.showMessageDialog(this, "Buena Inversion");
        }

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if (txtnucleos.getText().isEmpty() || txtbateria.getText().isEmpty() || txtgarantia.getText().isEmpty() || txtprecio.getText().isEmpty() || txtprincipal.getText().isEmpty() || txtram.getText().isEmpty() || txtsecundaria.getText().isEmpty() || txtpantalla.getText().isEmpty() || txtprecio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene los campos antes de Ejecutar el programa");
        } else {
            String cpu;
            cpu = txtnucleos.getText();

            if (cbxprincipal.isSelected() && cbxsecundaria.isSelected() && cbxflash.isSelected()) {
                texto.setText("Su numero de cpu es: " + cpu + "\nEl tamaño de la pantalla es: " + txtpantalla.getText() + "\nLa memoria RAM es de: " + txtram.getText() + "\nLa garantia es de: " + txtgarantia.getText() + "\nEl precio es de: " + txtprecio.getText() + "\nLa marca es: " + cmbmarca.getSelectedItem() + "\nPosee camara principal de " + txtprincipal.getText() + ", secundaria de " + txtsecundaria.getText() + " y flash");
            } else if (cbxprincipal.isSelected() && cbxsecundaria.isSelected()) {
                texto.setText("Su numero de cpu es: " + cpu + "\nEl tamaño de la pantalla es: " + txtpantalla.getText() + "\nLa memoria RAM es de: " + txtram.getText() + "\nLa garantia es de: " + txtgarantia.getText() + "\nEl precio es de: " + txtprecio.getText() + "\nLa marca es: " + cmbmarca.getSelectedItem() + "\nPosee camara principal de " + txtprincipal.getText() + " y secundaria de " + txtsecundaria.getText());
            } else if (cbxprincipal.isSelected() && cbxflash.isSelected()) {
                texto.setText("Su numero de cpu es: " + cpu + "\nEl tamaño de la pantalla es: " + txtpantalla.getText() + "\nLa memoria RAM es de: " + txtram.getText() + "\nLa garantia es de: " + txtgarantia.getText() + "\nEl precio es de: " + txtprecio.getText() + "\nLa marca es: " + cmbmarca.getSelectedItem() + "\nPosee camara principal de " + txtprincipal.getText() + " y flash");
            } else if (cbxsecundaria.isSelected() && cbxflash.isSelected()) {
                texto.setText("Su numero de cpu es: " + cpu + "\nEl tamaño de la pantalla es: " + txtpantalla.getText() + "\nLa memoria RAM es de: " + txtram.getText() + "\nLa garantia es de: " + txtgarantia.getText() + "\nEl precio es de: " + txtprecio.getText() + "\nLa marca es: " + cmbmarca.getSelectedItem() + "\nPosee camara secundaria de " + txtsecundaria.getText() + " y flash");
            } else if (cbxprincipal.isSelected()) {
                texto.setText("Su numero de cpu es: " + cpu + "\nEl tamaño de la pantalla es: " + txtpantalla.getText() + "\nLa memoria RAM es de: " + txtram.getText() + "\nLa garantia es de: " + txtgarantia.getText() + "\nEl precio es de: " + txtprecio.getText() + "\nLa marca es: " + cmbmarca.getSelectedItem() + "\nPosee camara principal de " + txtprincipal.getText());
            } else if (cbxsecundaria.isSelected()) {
                texto.setText("Su numero de cpu es: " + cpu + "\nEl tamaño de la pantalla es: " + txtpantalla.getText() + "\nLa memoria RAM es de: " + txtram.getText() + "\nLa garantia es de: " + txtgarantia.getText() + "\nEl precio es de: " + txtprecio.getText() + "\nLa marca es: " + cmbmarca.getSelectedItem() + "\nPosee camara secundaria de " + txtsecundaria.getText());
            } else if (cbxflash.isSelected()) {
                texto.setText("Su numero de cpu es: " + cpu + "\nEl tamaño de la pantalla es: " + txtpantalla.getText() + "\nLa memoria RAM es de: " + txtram.getText() + "\nLa garantia es de: " + txtgarantia.getText() + "\nEl precio es de: " + txtprecio.getText() + "\nLa marca es: " + cmbmarca.getSelectedItem() + "\nPosee camara con flash");
            } else {
                texto.setText("Su numero de cpu es: " + cpu + "\nEl tamaño de la pantalla es: " + txtpantalla.getText() + "\nLa memoria RAM es de: " + txtram.getText() + "\nLa garantia es de: " + txtgarantia.getText() + "\nEl precio es de: " + txtprecio.getText() + "\nLa marca es: " + cmbmarca.getSelectedItem() + "\nPosee camara principal de " + txtprincipal.getText() + ", secundaria de " + txtsecundaria.getText() + "y flash");
            }
            Impresion();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    int contador=0;
    private void txtnucleosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnucleosKeyTyped
        char tecla=evt.getKeyChar();
        int car=(int)evt.getKeyChar();
        
        if(txtnucleos.getText().length()==0 ){
            if(car<49 || car>57 ){
                if(car==8){
                    
                }
                else{
                  evt.consume();    
                }
              
            }
           
        }
         if(txtnucleos.getText().length()==1){
             
             int c=(int)txtnucleos.getText().charAt(0);
            if(c==49){
                if(car<48 || car>50){
                 evt.consume();   
                }
            }
            else {
                evt.consume();
            }
         }
        
        if(txtnucleos.getText().length()>1){
             evt.consume();
         }
        
    }//GEN-LAST:event_txtnucleosKeyTyped

    private void txtnucleosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnucleosActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtnucleosActionPerformed

    private void txtpantallaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpantallaKeyTyped
        // TODO add your handling code here:
         char tecla=evt.getKeyChar();
        int car=(int)evt.getKeyChar();
        System.out.println(""+car);
        if(txtpantalla.getText().length()==0 ){
            if(car<51 || car>54 ){
                if(car==8){
                    
                }
                else{
                  evt.consume();    
                }
              
            }
           
        }
         if(txtpantalla.getText().length()==1 && car!=46){
             evt.consume();
         }
        if(txtpantalla.getText().length()==2 ){
            int c=(int)txtpantalla.getText().charAt(0);
            if(c==54){
                if(car<48 || car>55){
                 evt.consume();   
                }
            }
             
         }
        if(txtpantalla.getText().length()>2){
             evt.consume();
         }
        if(car==46){
            for(int i=0;i<txtpantalla.getText().length();i++){
              int posicion=(int)txtpantalla.getText().charAt(i);
              if(posicion==46){
                  evt.consume();
              }
            }
            
        }
    }//GEN-LAST:event_txtpantallaKeyTyped

    private void txtpantallaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpantallaKeyPressed
        // TODO add your handling code here:
       
       
    }//GEN-LAST:event_txtpantallaKeyPressed

    private void txtramKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtramKeyTyped
        // TODO add your handling code here:
        char tecla=evt.getKeyChar();
        int car=(int)evt.getKeyChar();
       
        if(txtram.getText().length()==0 ){
            if(car<48 || car>54 ){
                if(car==8){
                    
                }
                else{
                  evt.consume();    
                }
              
            }
           
        }
         if(txtram.getText().length()==1 && car!=46){
             evt.consume();
         }
        if(txtram.getText().length()==2 ){
            int c=(int)txtram.getText().charAt(0);
            if(c==48){
                if(car<53 || car>57){
                 evt.consume();   
                }
            }
            else if(c==54 && car!=48){
                evt.consume();
            }
             
         }
        if(txtram.getText().length()>2){
             evt.consume();
         }
        if(car==46){
            for(int i=0;i<txtram.getText().length();i++){
              int posicion=(int)txtram.getText().charAt(i);
              if(posicion==46){
                  evt.consume();
              }
            }
            
        }
    }//GEN-LAST:event_txtramKeyTyped

    private void txtgarantiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgarantiaKeyTyped
        // TODO add your handling code here:
        char tecla=evt.getKeyChar();
        int car=(int)evt.getKeyChar();
        
        if(txtgarantia.getText().length()==0 ){
            if(car<49 || car>57 ){
                if(car==8){
                    
                }
                else{
                  evt.consume();    
                }
              
            }
           
        }
         if(txtgarantia.getText().length()==1){
             
             int c=(int)txtgarantia.getText().charAt(0);
            if(c==49){
                if(car<48 || car>57){
                 evt.consume();   
                }
            }
            else if(c==50){
                if(car<=48 || car>52){
                 evt.consume();   
                }
            }
            else{
                evt.consume();
            }
         }
        
        if(txtgarantia.getText().length()>1){
             evt.consume();
         }
        
    }//GEN-LAST:event_txtgarantiaKeyTyped

    private void txtprecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprecioKeyTyped
        // TODO add your handling code here:
        
        int car=(int)evt.getKeyChar();
        
        if(txtprecio.getText().length()==0 ){
            if(car<48 || car>57 ){
                if(car==8){
                    
                }
                else{
                  evt.consume();    
                }
              
            }
           
        }
         if(txtprecio.getText().length()==1){
             
             int c=(int)txtprecio.getText().charAt(0);
            if(c==48){
                if(car!=46){
                 evt.consume();   
                }
            }
            else {
                  
                
            }
         }
        if(txtprecio.getText().length()==3){
             
             int c=(int)txtprecio.getText().charAt(2);
            if(c==48){
                if(car<49 || car>57){
                 evt.consume();   
                }
            }
            
         }
        if(txtprecio.getText().length()==3){
            boolean punto=false;
           for(int i=0;i<txtprecio.getText().length();i++){
              int posicion=(int)txtprecio.getText().charAt(i);
              if(posicion==46 || car==46){
                  punto=true;
              }
            }
           if(punto==false){
               evt.consume();
           }
        }
        if(car==46){
            for(int i=0;i<txtprecio.getText().length();i++){
              int posicion=(int)txtprecio.getText().charAt(i);
              if(posicion==46){
                  evt.consume();
              }
            }
            
        }
        if(txtprecio.getText().length()>5){
             evt.consume();
         }
        
        else{
            
        }
    }//GEN-LAST:event_txtprecioKeyTyped

    private void txtramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtramActionPerformed

    private void cbxsecundariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxsecundariaActionPerformed
        // TODO add your handling code here:
         txtprincipal.setEnabled(true);
        txtprincipal.requestFocus();
    }//GEN-LAST:event_cbxsecundariaActionPerformed

    private void cbxflashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxflashActionPerformed
        // TODO add your handling code here:
         txtprincipal.setEnabled(true);
        txtprincipal.requestFocus();
    }//GEN-LAST:event_cbxflashActionPerformed

    private void txtprincipalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprincipalKeyTyped
        // TODO add your handling code here:
        int car=(int)evt.getKeyChar();
       
        if(txtprincipal.getText().length()==0 ){
            if(car<48 || car>57 ){
                if(car==8){
                    
                }
                else{
                  evt.consume();    
                }
              
            }
           
        }
         if(txtprincipal.getText().length()!=0){
            if(car==46){
                for(int i=0;i<txtprincipal.getText().length();i++){
              int posicion=(int)txtprincipal.getText().charAt(i);
              if(posicion==46){
                  evt.consume();
              }
            }
            }
         }
         if(txtprincipal.getText().length()>3){
             evt.consume();
         }
        
        
    }//GEN-LAST:event_txtprincipalKeyTyped

    private void txtbateriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbateriaKeyTyped
        char tecla=evt.getKeyChar();
        if(!Character.isDigit(tecla)){
            evt.consume();
        }
        if(txtbateria.getText().length()>3){
            evt.consume();
        }
    }//GEN-LAST:event_txtbateriaKeyTyped

    private void txtgarantiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgarantiaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtgarantiaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Ventanasecundaria v= new Ventanasecundaria();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtsecundariaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsecundariaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsecundariaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frmguia3y4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frmguia3y4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frmguia3y4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frmguia3y4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frmguia3y4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbxflash;
    private javax.swing.JCheckBox cbxprincipal;
    private javax.swing.JCheckBox cbxsecundaria;
    private javax.swing.JComboBox<String> cmbmarca;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea texto;
    private javax.swing.JTextField txtbateria;
    private javax.swing.JTextField txtgarantia;
    private javax.swing.JTextField txtnucleos;
    private javax.swing.JTextField txtpantalla;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtprincipal;
    private javax.swing.JTextField txtram;
    private javax.swing.JTextField txtsecundaria;
    // End of variables declaration//GEN-END:variables
}
